In [61]:
import pandas as pd

In [62]:
dict_data = {
    "c0": [1, 2, 3], 
    "c1": [4, 5, 6], 
    "c2": [7, 8, 9], 
    "c3": [10, 11, 12], 
    "c4": [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [63]:
# pandas.DataFrame(2차원배열, 
#                  index=행 인덱스 배열,
#                  columns=열 이름 배열
#                  )

arr = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"]
]

df = pd.DataFrame(arr, index=["준서", "예은"], columns=["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [64]:
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [65]:
#행 인덱스 변경
# DataFrame객체.index = 행 인덱스 배열
# DataFrame객체.columns = 열 인덱스 배열

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [66]:
df.index = ["학생1","학생2"]
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [67]:
df.columns=["연령","남녀","소속"]
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [68]:
# 행인덱스변경 : DataFrame객체.rename(index={기존 인덱스:새 인덱스})
# 열이름변경 : DataFrame객체.rename(cloumns={기존 이름:새 이름})
matrix=[
    [15,"남","덕영중"],
    [17,"여","수리중"]
]
df=pd.DataFrame(matrix, index=["준서","예은"],columns=["나이","성별","학교"])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [69]:
df.rename(columns={
    "나이":"연령",
    "성별":"남녀",
    "학교":"소속"
})
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [70]:
df=df.rename(index={
    "준서":"학생1",
    "예은":"학생2"
})
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [71]:
#행/열 삭제
#행 삭제: DataFrame 객체.drop(행 인덱스 또는 배열, axis=0또는 axis="index")
#열 삭제: DataFrame 객체.drop(열 이름 또는 배열, axis=1또는 axis="columns")
exam_data={'수학':[90,80,70], '영어':[98,89,95],
           '음악':[85,95,100],'체육':[100,90,90]}

df=pd.DataFrame(exam_data,index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [72]:
#우현 행을 드랍. (삭제)
df2=df.copy()
df2=df2.drop('우현')
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [73]:
df3=df.copy()
df3=df3.drop(["우현","인아"])
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [74]:
df4=df.copy()
df4=df4.drop(["우현","인아"],axis='index')
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [75]:
df5=df.copy()
df5=df5.drop(index=["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [76]:
exam_data={'수학':[90,80,70], '영어':[98,89,95],
           '음악':[85,95,100],'체육':[100,90,90]}

df=pd.DataFrame(exam_data,index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [77]:
df2=df.copy()
df2=df2.drop("수학",axis=1)
df2

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [78]:
df3=df.copy()
df3=df3.drop(['영어','음악'],axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [79]:
df4=df.copy()
df4=df4.drop(['영어','음악'],axis='columns')
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [80]:
df5=df.copy()
df5=df5.drop(columns=["수학","영어"])
df5

     음악   체육
서준   85  100
우현   95   90
인아  100   90

In [81]:
#행 선택
exam_data={'수학':[90,80,70], '영어':[98,89,95],
           '음악':[85,95,100],'체육':[100,90,90]}

df=pd.DataFrame(exam_data,index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [82]:
#열 이름으로 선택
labell=df.loc['서준']
print(labell)
print(type(labell)) #시리즈 타입

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [83]:
#인덱싱으로도 가능
position1=df.iloc[0]
print(position1)
print(type(position1))

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64
<class 'pandas.Series'>

In [84]:
label2=df.loc[["서준","우현"]]
print(label2)
print(type(label2))#데이터프레임 타입.

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [85]:
label3=df.loc[["서준"]]
print(label3)
print(type(label3))#하나만 가지고 와도 [[]]를 쓰면 데이터프레임 타입임.

    수학  영어  음악   체육
서준  90  98  85  100
<class 'pandas.DataFrame'>

In [86]:
position2=df.iloc[[0,1]]
print(position2)
print(type(position2))

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90
<class 'pandas.DataFrame'>

In [87]:
#행 선택 슬라이싱 하기
label4=df.loc['서준':'우현']#우현 포함
print(label4)

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [88]:
position3=df.iloc[0:2]#인아 미포함
position3

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [89]:
#열 선택
exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}

df=pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [90]:
math1=df["수학"]
print(math1)

0    90
1    80
2    70
Name: 수학, dtype: int64

In [91]:
eng=df.영어 #제목이 영어가 아니라 영 어라면, 에러 발생. 띄어쓰기가 있으면 대괄호 안에 넣어야 함.
eng

0    98
1    89
2    95
Name: 영어, dtype: int64

In [92]:
mus_gym=df[['음악','체육']]
mus_gym

    음악   체육
0   85  100
1   95   90
2  100   90

In [93]:
math2=df[['수학']] #한가지 데이터지만 데이터프레임 타입. 
print(type(math2)) #시리즈는 1차원, 데이터프레임은 2차원이다.
math2

<class 'pandas.DataFrame'>

   수학
0  90
1  80
2  70

In [94]:
#범위 슬라이싱
exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}

df=pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [95]:
df.iloc[::2]

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
2  인아  70  95  100   90

In [96]:
df.iloc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   85  100

In [97]:
#원소 선택
import pandas as pd

exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}
df=df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [107]:
#원소 선택 : 행과 열 선택하기
a=df.loc["서준","음악"]
b=df.iloc[0,2]
print(a,b)

85 85

In [105]:
#두개 이상의 값 가져오기.
#아래 c d e f 는 모두 같은 값을 불러옴.
c=df.loc['서준',['음악','체육']]
print(c)
d=df.iloc[0,[2,3]]
print(d)
e=df.loc['서준','음악':'체육']
print(e)
f=df.iloc[0,2:]
print(f)

음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64
음악     85
체육    100
Name: 서준, dtype: int64

In [114]:
#떨어져있는 요소 가져오기
g=df.loc[['서준','우현'],['음악','체육']]
print(g)
h=df.iloc[[0,1],[2,3]]
print(h)
i=df.loc['서준':'우현','음악':'체육']
print(i)
j=df.iloc[0:2,2:]
print(j)

    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90
    음악   체육
이름
서준  85  100
우현  95   90

In [116]:
#열 추가
import pandas as pd

exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}
df=pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [119]:
#국어 라는 과목의 열 추가.
df['국어']=80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [123]:
#미술 추가, 점수 각각 지정
df['미술']=[80,90,100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [124]:
#행 추가
import pandas as pd

exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}
df=pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [126]:
#싹다 0인 행 추가
df.loc[3]=0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [127]:
#동규라는 학생 성적 추가
df.loc[4]=['동규',90,80,70,60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [131]:
#새로운 행 추가+기존 값 복사
df.loc['5행']=df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
5행   0   0   0    0    0

In [129]:
### loc 와 iloc의 인덱싱 차이
print(df.loc[0:2])
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [ ]:
#원소 값 변경하기
import pandas as pd

exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}
df=pd.DataFrame(exam_data)
df=df.set_index('이름')
print(df)
df.iloc[0,3]=80
print(df)
df.loc['서준','체육']=90
print(df)

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [13]:
df.loc['서준',['음악','체육']]=50
print(df)

df.loc['서준',['음악','체육']]=100,50
print(df)

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90
    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [21]:
#행, 열 위치 바꾸기
import pandas as pd

exam_data={
    '이름':['서준','우현','인아'],
    '수학':[90,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
    '체육':[100,90,90]
}
df=pd.DataFrame(exam_data)
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [22]:
#df를 전치하기
df=df.transpose()
print(df)

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [23]:
df=df.T
print(df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90