In [2]:
import pandas as pd

In [3]:
dict_data={
    "국어":100,
    "영어":80,
    "수학":90
}

student1=pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [ ]:
#시리즈와 숫자 연산
persentage=student1/200
print(persentage)
print(type(persentage))

국어    0.50
영어    0.40
수학    0.45
dtype: float64
<class 'pandas.Series'>

In [6]:
#시리즈 시리즈 연산
student1=pd.Series({
    "국어":100,
    "영어":80,
    "수학":90
})
student2=pd.Series({
    "수학":80,
    "국어":90,
    "영어":80,  
})
print(student1)
print(student2)

국어    100
영어     80
수학     90
dtype: int64
수학    80
국어    90
영어    80
dtype: int64

In [ ]:
#순서가 달라도 같은 국어, 수학, 영어 점수를 더함. (/*-+ 모두 가능)
print(student1+student2)
print(type(student1+student2))

국어    190
수학    170
영어    160
dtype: int64
<class 'pandas.Series'>

In [ ]:
#Nan값이 있는 시리즈 연산 (Nan=값이 없음)
import pandas as pd
import numpy as np
student1=pd.Series({'국어':np.nan,'영어':80,'수학':90})
student2=pd.Series({'수학':80,'국어':90})
print(student1)
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
dtype: int64

In [9]:
add=student1+student2
sub=student1-student2
mul=student1*student2
div=student1/student2
print(add, sub, mul, div)

국어      NaN
수학    170.0
영어      NaN
dtype: float64 국어     NaN
수학    10.0
영어     NaN
dtype: float64 국어       NaN
수학    7200.0
영어       NaN
dtype: float64 국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [10]:
result=pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [18]:
#연산 메소드
#두 사람의 과목별 점수로 사칙연산
sr_add=student1.add(student2,fill_value=0)
sr_sub=student1.sub(student2,fill_value=0)
sr_mul=student1.mul(student2,fill_value=0)
sr_div=student1.div(student2,fill_value=0)
result=pd.DataFrame([sr_add,sr_sub,sr_mul,sr_div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [1]:
#데이터프레임 연산
import pandas as pd
import seaborn as sns

In [2]:
titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','fare']]
print(df.head())
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
<class 'pandas.DataFrame'>

In [3]:
#데이터프레인에 숫자 더하기
addition=df+10
print(addition.head())
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500
<class 'pandas.DataFrame'>

In [4]:
#데이터프레임끼리 더하기
import pandas as pd
import seaborn as sns

titanic=sns.load_dataset('titanic')
df=titanic.loc[:,['age','fare']]
print(df.tail())
print(type(df))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75
<class 'pandas.DataFrame'>

In [5]:
add=df+10
print(add.tail)

<bound method NDFrame.tail of       age     fare
0    32.0  17.2500
1    48.0  81.2833
2    36.0  17.9250
3    45.0  63.1000
4    45.0  18.0500
..    ...      ...
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

[891 rows x 2 columns]>

In [7]:
sub=add-df
print(sub.tail())

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [ ]:
#
sample1=add.tail()
sample2=sub.tail().fillna(0.0)
print(sample1)
print(sample2)

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75
      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [12]:
df_add=sample1.add(sample2,fill_value=0)
df_sub=sample1.sub(sample2,fill_value=0)
df_mul=sample1.mul(sample2,fill_value=0)
df_div=sample1.div(sample2,fill_value=0)
print(df_add)
print(df_sub)
print(df_mul)
print(df_div)

      age   fare
886  47.0  33.00
887  39.0  50.00
888   0.0  43.45
889  46.0  50.00
890  52.0  27.75
      age   fare
886  27.0  13.00
887  19.0  30.00
888   0.0  23.45
889  26.0  30.00
890  32.0   7.75
       age   fare
886  370.0  230.0
887  290.0  400.0
888    0.0  334.5
889  360.0  400.0
890  420.0  177.5
     age   fare
886  3.7  2.300
887  2.9  4.000
888  NaN  3.345
889  3.6  4.000
890  4.2  1.775