In [12]:
import pandas as pd

In [2]:
# 1. df 라는 이름의 데이터프레임을 만들어 주세요
df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
})

df

    이름  나이 성별   수학  영어
0  김철수  20  남   90  85
1  이영희  21  여   85  95
2  박민수  22  남   70  75
3  최지우  20  여  100  90

In [14]:
# 2. 생성된 데이터프레임의 상위 2개 행만 출력하세요.
type(df)
df1=df.iloc[0:2]
print(df1)
df.head(2)

     나이 성별  수학  영어
이름
김철수  20  남  90  85
이영희  21  여  85  95

     나이 성별  수학  영어
이름
김철수  20  남  90  85
이영희  21  여  85  95

In [20]:
# 3. 데이터프레임의 요약 정보(컬럼명, 데이터 타입 )을 확인하세요
print(df.columns)
print(df.dtypes)

df.info()

Index(['나이', '성별', '수학', '영어'], dtype='str')
나이    int64
성별      str
수학    int64
영어    int64
dtype: object
<class 'pandas.DataFrame'>
Index: 4 entries, 김철수 to 최지우
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   나이      4 non-null      int64
 1   성별      4 non-null      str
 2   수학      4 non-null      int64
 3   영어      4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 332.0+ bytes

In [5]:
# 4. '이름' 컬럼을 인덱스로 설정하세요. (기존 df를 수정)
df=df.set_index('이름')
df

     나이 성별   수학  영어
이름
김철수  20  남   90  85
이영희  21  여   85  95
박민수  22  남   70  75
최지우  20  여  100  90

In [21]:
# 5. loc을 사용하여 '이영희'의 '수학' 점수와 '영어' 점수만 추출하세요.
df2=df.loc['이영희', ['수학', '영어']]
df2

수학    85
영어    95
Name: 이영희, dtype: int64

In [9]:
# 6. iloc을 사용하여 첫 번째 행부터 두 번째 행까지, 그리고 2번째 열(수학)부터 마지막 열까지 슬라이싱하세요.
df3=df.iloc[0:2, 2:]
df3

     수학  영어
이름
김철수  90  85
이영희  85  95

In [11]:
# 1. 위 데이터로 시리즈 객체 sr을 만들어주세요
import pandas as pd

data = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

sr = pd.Series(data)

print(sr)

이름    [김철수, 이영희, 박민수, 최지우]
나이        [20, 21, 22, 20]
성별            [남, 여, 남, 여]
수학       [90, 85, 70, 100]
영어        [85, 95, 75, 90]
dtype: object

In [23]:
# 2. 시리즈의 인덱스 배열과 데이터값 배열을 각각 추출하여 화면에 출력하세요.
print(sr.index)
print(sr.values)

Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')
[list(['김철수', '이영희', '박민수', '최지우']) list([20, 21, 22, 20])
 list(['남', '여', '남', '여']) list([90, 85, 70, 100]) list([85, 95, 75, 90])]

In [26]:
list_data = ["2010-01-02", 3.14, "ABC", 100, True]
# 3. 위 데이터를 시리즈 객체로 만들어 주세요
sr=pd.Series(list_data)

In [27]:
# 4. 데이터 타입을 출력헤보세요
sr.dtype

dtype('O')

In [28]:
tup_data = ("영인", "2010-05-01", "여", True)
index_labels = ["이름", "생년월일", "성별", "학생여부"]
# 5. 위 데이터를 시리즈객체로 생성해주세요. 
sr=pd.Series(tup_data,index=index_labels)
print(sr)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [31]:
# 6. 해당 시리즈의 원소 개수, 형상(shape), 차원을 출력해주세요
print(sr.size)
print(sr.shape)
print(sr.ndim)

4
(4,)
1

In [33]:
# 7. 위치 기반(정수)으로 첫 번째 원소를 안전하게 조회하는 코드를 작성하세요. (iloc 활용)
sr.iloc[0]

'영인'

In [35]:
# 8. 라벨 '이름'으로 원소를 조회하는 코드를 작성하세요.
print(sr.loc["이름"])
print(sr["이름"])

영인
영인

In [36]:
# 9. 위치 인덱스 번호 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요. (iloc 권장)
print(sr.iloc[[1,2]])

생년월일    2010-05-01
성별               여
dtype: object

In [38]:
# 10. 라벨 이름 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요.
print(sr[["생년월일","성별"]])

생년월일    2010-05-01
성별               여
dtype: object

In [39]:
# 11. 아무 데이터도 전달하지 않은 기본형 빈 시리즈를 생성하세요.
sr=pd.Series()
print(sr)

Series([], dtype: object)

In [42]:
# 12. 스칼라 값 5와 인덱스 ["a", "b", "c"]를 사용하여 시리즈를 생성하고 출력하세요.
sr=pd.Series(5,index=['a','b','c'])
print(sr)

a    5
b    5
c    5
dtype: int64

In [44]:
# 1. 아래 주어진 리스트 데이터를 활용하여 각각 1차원 배열 arr1과 2차원 배열 arr2를 생성하고 타입을 출력하세요.
list1 = [1, 2, 3, 4, 5]
list2 = [
    [1, 2, 3], 
    [4, 5, 6]
]

import numpy as np

arr1=np.array(list1)
arr2=np.array(list2)

print(arr1)
print(arr2)
print(type(arr1))
print(arr1.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64

In [45]:
# 2. 모든 원소가 0.으로 채워진 크기 5짜리 1차원 배열 zeros 생성
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]

In [46]:
# 3. 모든 원소가 1.으로 채워진 크기 2행 3열의 2차원 배열 ones 생성
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]

In [48]:
# 4. 1부터 시작하여 2씩 증가하며 10 미만인 정수로 구성된 배열 range_arr 생성
range_arr=np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]

In [50]:
arr3 = np.array([
    [[1, 2],
     [3, 4]], 
    [[5, 6],
     [7, 8]]
])
# 5. 배열 속성(dtype, shape, ndim, size) 출력해주세요
print(arr3.dtype)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

int64
(2, 2, 2)
3
8

In [51]:
arr_base = np.array([1, 2, 3, 4, 5, 6])
# 6. 위 1차원 배열을 2차원 배열로 변경해주세요
reshaped=arr_base.reshape((2,3))
print(reshaped)

[[1 2 3]
 [4 5 6]]

In [54]:
# 7. 배열의 데이터 타입을 실수형(float)으로 변경하여 float_arr에 저장하세요.
print(arr_base.dtype)
arr_base=arr_base.astype(float)
print(arr_base.dtype)

int64
float64

In [57]:
arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
# 8. ravel을 사용해 1차원 배열로 평탄화하여 출력하세요.
print(arr_2d)
print(arr_2d.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

In [58]:
# 9. flatten을 사용해 1차원 배열로 평탄화하여 출력하세요.
print(arr_2d.flatten())

[1 2 3 4 5 6]

In [61]:
# 10. 축을 바꾸어 3행2열 -> 2행 3열로 만들어주세요 
print(arr_2d.transpose())
print(arr_2d.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

In [63]:
arr_x = np.array([5, 3, 3])
arr_y = np.array([1, 2, 6])
# 11. arr_x와 arr_y의 요소별 합(+)과 요소별 곱(*)을 각각 계산해 출력하세요.
print(arr_x+arr_y)
print(arr_x*arr_y)

[6 5 9]
[ 5  6 18]

In [64]:
# 12. arr_x가 arr_y보다 큰지 여부를 비교하는 비교 연산 결과를 출력하세요.
print(arr_x>arr_y)

[ True  True False]

In [65]:
# 13. arr_x에 단일 스칼라 값 2를 곱하여 모든 요소가 2배가 되도록 출력하세요.
print(arr_x*2)

[10  6  6]

In [67]:
data = np.array([1, 2, 3, 4, 5])
# 14. data 배열에서 2보다 큰 원소들만 추출하세요.
cond=data>2
data[cond]

array([3, 4, 5])

In [73]:
# 15. data 배열에서 2보다 크면서 동시에 5보다 작은 원소들만 추출하세요. (비트 연산자 & 활용)
cond=(data>2) & (data<5)
print(data[cond])

[3 4]

In [80]:
stats_arr = np.array([1, 2, 3, 4])
# 16. 합계, 평균, 분산, 표준편차, 중앙값을 구하세요
print(stats_arr.sum()) #합계
print(np.sum(stats_arr)) #합계
print(np.mean(stats_arr)) #평균
print(np.var(stats_arr)) #분산
print(np.std(stats_arr)) #표준편차
print(np.median(stats_arr)) #중앙값

10
10
2.5
1.25
1.118033988749895
2.5