In [5]:
import pandas as pd

In [8]:
url='../data/sample.html'
tables=pd.read_html(url)
print(len(tables))
for i in range(len(tables)):
    print("tables[%s]"%i)
    print(tables[i])
    print('\n')

2
tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9


tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [13]:
df=tables[1]
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [14]:
df=df.set_index(['name'])
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True

In [29]:
#웹스크래핑
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
header={"user-agent":agent}
url="https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds"
resp = requests.get(url,headers=header)
soup=BeautifulSoup(resp.text,"lxml")
rows=soup.select('div>ul>li')#li 중 div 밑 ul 밑 li 만 찾는다.
                             #클래스면 div.클래스이름, ID면 div#아이디

print("rows: ", rows[50:55])

rows:  [<li><a href="/wiki/Category:Articles_with_short_description" title="Category:Articles with short description">Articles with short description</a></li>, <li><a href="/wiki/Category:Short_description_is_different_from_Wikidata" title="Category:Short description is different from Wikidata">Short description is different from Wikidata</a></li>, <li><a href="/wiki/Category:Dynamic_lists" title="Category:Dynamic lists">Dynamic lists</a></li>, <li><a href="/wiki/Category:Wikipedia_articles_needing_clarification_from_January_2024" title="Category:Wikipedia articles needing clarification from January 2024">Wikipedia articles needing clarification from January 2024</a></li>, <li><a href="/wiki/Category:All_articles_with_unsourced_statements" title="Category:All articles with unsourced statements">All articles with unsourced statements</a></li>]

In [ ]:
etfs={}

for row in rows:
    
    try:
        etf_name = re.findall("(.+?)\s\(", row.text)
        etf_market = re.findall("\((.+?):", row.text)
        etf_ticker = re.findall(":\s(.+)\)", row.text)
        
        if (len(etf_ticker) > 0) & (len(etf_market) > 0) & (len(etf_name) > 0):
            etfs[etf_ticker[0]] = [etf_market[0], etf_name[0]]

    except AttributeError as err:
        pass

print(etfs)

{}

<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:7: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:8: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<>:7: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:8: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
C:\Users\KDS13\AppData\Local\Temp\ipykernel_14480\1619506246.py:6: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  etf_name = re.findall("(.+?)\s\(", row.text)
C:\Users\KDS13\AppData\Local\Temp\ipykernel_14480\1619506246.py:7: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  etf_market = re.findall("\((.+?):", row.text)
C:\Users\KDS13\AppData\Local\Temp\ipykernel_14480\1619506246.py:8: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
  etf_ticker = re.findall(":\s(.+)\)", row.text)