In [9]:
import requests
import pandas as pd

my_key = "dpd-f9b30098-0fffe13acd6bf71c3020bcc0e2de2526fb63d2a93cf9347f57d8ee3c00d3b2b2"

# 특정 종목(stockCode)의 재무항목(indicatorName) 데이터를 가져오는 함수를 정의
def get_financials(stockCode, indicatorName, apiKey, consolidated=True, ttm=True):    
    if consolidated:   # 연결 기준
        if ttm:        # Trailing 12 Months (12개월 누적)
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByTTM?indicatorName={indicatorName}&stockCode={stockCode}"
                        
        else:          # 해당 분기 기준 (3개월 집계)
            url = f"https://api.dapada.io/company/getConsolidatedFinancialDataByCUR?indicatorName={indicatorName}&stockCode={stockCode}"       
            
    else:              # 별도 기준
        if ttm:        # Trailing 12 Months (12개월 누적)
            url = f" https://api.dapada.io/company/getSeparatedFinancialDataByTTM?indicatorName={indicatorName}&stockCode={stockCode}"            
        else:          # 해당 분기 기준 (3개월 집계)
            url = f" https://api.dapada.io/company/getSeparatedFinancialDataByCUR?indicatorName={indicatorName}&stockCode={stockCode}"       
           
    headers = {"Authorization": f"{apiKey}"}
    response = requests.get(url, headers=headers)
    result = response.json()
    return pd.DataFrame(result)

# 삼성전자(005930)의 연결 재무제표 (TTM 기준)에서 "매출액" 항목의 데이터 수집
df_ttm_consolidated = get_financials(stockCode='005930',
                                     indicatorName='매출액',
                                     apiKey=my_key,
                                     consolidated=True,
                                     ttm=True)
df_ttm_consolidated

             value  quarter
0  261620131000000  2023-Q3
1  270997159000000  2023-Q2
2  288195233000000  2023-Q1
3  302231360000000  2022-Q4
4  308332309000000  2022-Q3
5  305529816000000  2022-Q2
6  291997794000000  2022-Q1

In [10]:
# 삼성전자(005930)의 연결 재무제표 (분기 기준)에서 "매출액" 항목의 데이터 수집
df_cur_consolidated = get_financials(stockCode='005930', 
                                     indicatorName='매출액', 
                                     apiKey=my_key, 
                                     consolidated=True, 
                                     ttm=False)

df_cur_consolidated

            value  quarter
0  67404652000000  2023-Q3
1  60005533000000  2023-Q2
2  63745371000000  2023-Q1
3  70464575000000  2022-Q4
4  76781680000000  2022-Q3
5  77203607000000  2022-Q2
6  77781498000000  2022-Q1